pod 'AFNetworking'
pod 'Masonry'
pod 'SVPullToRefresh'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Fabric'
pod 'Crashlytics'
pod 'HockeySDK', '~> 3.8.5'
pod 'youtube-ios-player-helper', '~> 0.1.5'
