# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.48.0"

default_platform :ios

platform :ios do
  before_all do |lane, options|

    clear_derived_data
    disable_automatic_code_signing(path: "Push.xcodeproj")
    project_path="../Push.xcodeproj"

    

    if(lane != :offline && lane != :add_devices && lane != :create)
      #cocoapods 
      
        increment_build_number()
      
    end

    # xctool # run the tests of your app
  end

  desc "Runs all the tests"
  lane :test do
    snapshot
  end
  
  desc "Creates App"



  lane :create do
    produce(
      username: "guessc@missouri.edu",
      app_identifier: "com.occrp.meydan",
      app_name: "Meydan TV",
      language: "Russian,English"
    )
  end

  desc "Adds devices"
  lane :add_devices do
    register_devices(
        devices: {
            "Christopher Guess" => "b725c07c5e9799a9f824d544abc2534d9d317884"
        }
    )
  end

  desc "Creates development and stuff"
  lane :bootstrap do |options|
    cert(
      username: 'guessc@missouri.edu',
      development: true
    )

    produce(
      username: "guessc@missouri.edu",
      app_identifier: "com.occrp.meydan",
      company_name: "Journalism Development Network",
      app_name: "Meydan TV",
      language: "Russian,English"
    )

    sigh(
      development: true,
      force: true,
      username: "guessc@missouri.edu",
      app_identifier: "com.occrp.meydan"
    )


    
    # use the UID of the newly created provisioning profile
    # ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

    update_project_provisioning(
    )

  end


  desc "Used to test the generator"
  lane :gen_test do |options|
    cert(
      username: 'guessc@missouri.edu',
    )

    sigh(
      adhoc: true,
      force: true,
      username: "guessc@missouri.edu",
      app_identifier: "com.occrp.meydan"
    )
    
    # use the UID of the newly created provisioning profile
    # ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

    update_project_provisioning(
    )

    gym(
      export_method: "development",
      clean: true,
      scheme: 'Push',
    )
  end

  desc "Used to test the generator when offline"
  lane :offline do |options|
    # use the UID of the newly created provisioning profile
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

    gym(
      export_method: "development",
      clean: true,
      scheme: 'Push',
    )
  end

  desc "Submit a new Beta Build to HockeyApp"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    cert(
      username: 'guessc@missouri.edu',
    )
    sigh(
      force: true,
      username: "guessc@missouri.edu",
      app_identifier: "com.occrp.meydan"
    )
    
    # use the UID of the newly created provisioning profile
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

    update_project_provisioning(
        xcodeproj: 'build_files/ios/project/Push.xcodeproj',
        target_filter: '.*',
        build_configuration: '.*'
    )

    gym(
      export_method: "ad-hoc",
      clean: true,
      scheme: 'Push',
      
    ) # Build your app - more options available

    #hockey(
    #  api_token: "5e6b858b240b43a7938de3d7397d4045",
    #  notes: options[:notes],
    #  #public_identifier: "5e1c7f0b67b4472c8590cb292a77ba25"
    #)
    pilot(
      changelog: options[:notes]
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    #ensure_no_debug_code(text: "NSLog")
    cert(
      username: 'guessc@missouri.edu',
    )
    #snapshot
    sigh(
	    force: true,
    	username: "guessc@missouri.edu",
    	app_identifier: "com.occrp.meydan",
    )

    update_project_provisioning(
    )

    gym(
        scheme: "Push",
        export_method: "app-store",
	      clean: true,
        include_symbols: true,
        include_bitcode: true,
    )
    deliver(
    	force: true,
    	username: "guessc@missouri.edu",
    )

  end

  after_all do |lane|
    enable_automatic_code_signing(path: "Push.xcodeproj")

    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    enable_automatic_code_signing(path: "Push.xcodeproj")

    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
