//
//  About.h
//  Push
//
//  Created by Christopher Guess on 1/26/16.
//  Copyright (c) 2016 OCCRP. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface About : NSObject

// Drawing Methods
+ (void)drawIOval1Canvas;

@end
