//
//  About.m
//  Push
//
//  Created by Christopher Guess on 1/26/16.
//  Copyright (c) 2016 OCCRP. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "About.h"


@implementation About

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawIOval1Canvas
{
    //// Color Declarations
    UIColor* strokeColor = [UIColor colorWithRed: 0.638 green: 0.072 blue: 0.126 alpha: 1];

    //// Group
    {
        //// Group 2
        {
            //// Group 3
            {
                //// Page-1
                {
                    //// i-+-Oval-1
                    {
                        //// Oval-1 Drawing
                        UIBezierPath* oval1Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(11, 6, 18, 18)];
                        [strokeColor setStroke];
                        oval1Path.lineWidth = 1.5;
                        [oval1Path stroke];
                    }
                }


                //// Text Drawing
                UIBezierPath* textPath = [UIBezierPath bezierPath];
                [textPath moveToPoint: CGPointMake(21.2, 13.31)];
                [textPath addLineToPoint: CGPointMake(21.2, 19.5)];
                [textPath addCurveToPoint: CGPointMake(20.89, 20.47) controlPoint1: CGPointMake(21.2, 19.93) controlPoint2: CGPointMake(21.1, 20.25)];
                [textPath addCurveToPoint: CGPointMake(20.11, 20.8) controlPoint1: CGPointMake(20.69, 20.69) controlPoint2: CGPointMake(20.43, 20.8)];
                [textPath addCurveToPoint: CGPointMake(19.35, 20.46) controlPoint1: CGPointMake(19.8, 20.8) controlPoint2: CGPointMake(19.54, 20.69)];
                [textPath addCurveToPoint: CGPointMake(19.05, 19.5) controlPoint1: CGPointMake(19.15, 20.24) controlPoint2: CGPointMake(19.05, 19.91)];
                [textPath addLineToPoint: CGPointMake(19.05, 13.37)];
                [textPath addCurveToPoint: CGPointMake(19.35, 12.41) controlPoint1: CGPointMake(19.05, 12.95) controlPoint2: CGPointMake(19.15, 12.63)];
                [textPath addCurveToPoint: CGPointMake(20.11, 12.09) controlPoint1: CGPointMake(19.54, 12.2) controlPoint2: CGPointMake(19.8, 12.09)];
                [textPath addCurveToPoint: CGPointMake(20.89, 12.41) controlPoint1: CGPointMake(20.43, 12.09) controlPoint2: CGPointMake(20.69, 12.2)];
                [textPath addCurveToPoint: CGPointMake(21.2, 13.31) controlPoint1: CGPointMake(21.1, 12.63) controlPoint2: CGPointMake(21.2, 12.93)];
                [textPath closePath];
                [textPath moveToPoint: CGPointMake(20.14, 11.09)];
                [textPath addCurveToPoint: CGPointMake(19.37, 10.82) controlPoint1: CGPointMake(19.84, 11.09) controlPoint2: CGPointMake(19.58, 11)];
                [textPath addCurveToPoint: CGPointMake(19.05, 10.04) controlPoint1: CGPointMake(19.16, 10.64) controlPoint2: CGPointMake(19.05, 10.38)];
                [textPath addCurveToPoint: CGPointMake(19.38, 9.29) controlPoint1: CGPointMake(19.05, 9.74) controlPoint2: CGPointMake(19.16, 9.49)];
                [textPath addCurveToPoint: CGPointMake(20.14, 9) controlPoint1: CGPointMake(19.59, 9.1) controlPoint2: CGPointMake(19.85, 9)];
                [textPath addCurveToPoint: CGPointMake(20.88, 9.27) controlPoint1: CGPointMake(20.42, 9) controlPoint2: CGPointMake(20.66, 9.09)];
                [textPath addCurveToPoint: CGPointMake(21.2, 10.04) controlPoint1: CGPointMake(21.09, 9.44) controlPoint2: CGPointMake(21.2, 9.7)];
                [textPath addCurveToPoint: CGPointMake(20.88, 10.82) controlPoint1: CGPointMake(21.2, 10.37) controlPoint2: CGPointMake(21.09, 10.63)];
                [textPath addCurveToPoint: CGPointMake(20.14, 11.09) controlPoint1: CGPointMake(20.67, 11) controlPoint2: CGPointMake(20.43, 11.09)];
                [textPath closePath];
                [strokeColor setFill];
                [textPath fill];
            }
        }
    }
}

@end
