//
//  LanguageButton.m
//  Push
//
//  Created by Christopher Guess on 8/29/17.
//  Copyright (c) 2017 ChrisGuess. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "LanguageButton.h"
#import "SettingsManager.h"

@implementation LanguageButton

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1
{
    //// Color Declarations
    UIColor* color = [SettingsManager sharedManager].navigationTextColor;
    
    //// Group
    {
        //// Oval Drawing
        UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(11, 5, 19, 19)];
        [color setStroke];
        ovalPath.lineWidth = 1;
        [ovalPath stroke];
        
        
        //// Oval 2 Drawing
        UIBezierPath* oval2Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(16, 5, 9, 19)];
        [color setStroke];
        oval2Path.lineWidth = 1;
        [oval2Path stroke];
        
        
        //// Bezier Drawing
        UIBezierPath* bezierPath = [UIBezierPath bezierPath];
        [bezierPath moveToPoint: CGPointMake(11.69, 10.35)];
        [bezierPath addLineToPoint: CGPointMake(29.14, 10.35)];
        [color setStroke];
        bezierPath.lineWidth = 1;
        [bezierPath stroke];
        
        
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = [UIBezierPath bezierPath];
        [bezier2Path moveToPoint: CGPointMake(11, 14.5)];
        [bezier2Path addLineToPoint: CGPointMake(30, 14.5)];
        [color setStroke];
        bezier2Path.lineWidth = 1;
        [bezier2Path stroke];
        
        
        //// Bezier 3 Drawing
        UIBezierPath* bezier3Path = [UIBezierPath bezierPath];
        [bezier3Path moveToPoint: CGPointMake(11.69, 18.82)];
        [bezier3Path addLineToPoint: CGPointMake(29.14, 18.82)];
        [color setStroke];
        bezier3Path.lineWidth = 1;
        [bezier3Path stroke];
    }

}

@end
