//
//  LanguageButton.h
//  Push
//
//  Created by Christopher Guess on 8/29/17.
//  Copyright (c) 2017 ChrisGuess. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface LanguageButton : NSObject

// Drawing Methods
+ (void)drawCanvas1;

@end
