//
//  PauseButton.h
//  Push
//
//  Created by Christopher Guess on 2/3/16.
//  Copyright (c) 2016 OCCRP. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PauseButton : NSObject

// Drawing Methods
+ (void)drawCanvas1WithFrame: (CGRect)frame;

@end
