//
//  PauseButton.m
//  Push
//
//  Created by Christopher Guess on 2/3/16.
//  Copyright (c) 2016 OCCRP. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "PauseButton.h"


@implementation PauseButton

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1WithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 0.275];
    CGFloat colorRGBA[4];
    [color getRed: &colorRGBA[0] green: &colorRGBA[1] blue: &colorRGBA[2] alpha: &colorRGBA[3]];
    
    UIColor* color3 = [UIColor colorWithRed: (colorRGBA[0] * 0.7 + 0.3) green: (colorRGBA[1] * 0.7 + 0.3) blue: (colorRGBA[2] * 0.7 + 0.3) alpha: (colorRGBA[3] * 0.7 + 0.3)];
    
    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.07692 + 0.5), CGRectGetMinY(frame) + 1, floor(CGRectGetWidth(frame) * 0.38462 + 0.5) - floor(CGRectGetWidth(frame) * 0.07692 + 0.5), floor((CGRectGetHeight(frame) - 1) * 0.93750 + 0.5))];
    [color3 setFill];
    [rectanglePath fill];
    [UIColor.darkGrayColor setStroke];
    rectanglePath.lineWidth = 2;
    [rectanglePath stroke];
    
    
    //// Rectangle 2 Drawing
    UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.61538 + 0.5), CGRectGetMinY(frame) + 1, floor(CGRectGetWidth(frame) * 0.92308 + 0.5) - floor(CGRectGetWidth(frame) * 0.61538 + 0.5), floor((CGRectGetHeight(frame) - 1) * 0.93750 + 0.5))];
    [color3 setFill];
    [rectangle2Path fill];
    [UIColor.darkGrayColor setStroke];
    rectangle2Path.lineWidth = 2;
    [rectangle2Path stroke];


}

@end
