//
//  PlayButton.m
//  ProjectName
//
//  Created by Christopher Guess on 2/3/16.
//  Copyright (c) 2016 OCCRP. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "PlayButton.h"


@implementation PlayButton

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1WithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 0.275];
    
    //// Polygon Drawing
    UIBezierPath* polygonPath = [UIBezierPath bezierPath];
    [polygonPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.92308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45996 * CGRectGetHeight(frame))];
    [polygonPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.24038 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88235 * CGRectGetHeight(frame))];
    [polygonPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.24038 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03758 * CGRectGetHeight(frame))];
    [polygonPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.92308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45996 * CGRectGetHeight(frame))];
    [polygonPath closePath];
    [color setFill];
    [polygonPath fill];
    [UIColor.darkGrayColor setStroke];
    polygonPath.lineWidth = 2;
    [polygonPath stroke];
}


@end
